### PR TITLE
Adding README.md

### PR DESCRIPTION
**Pull request by kingtigerwin**
Hi all,

Please help review my PR.

This PR is just adding one README.md file.

### CODE REVIEW

**Comment by whisperice** [comment]
Now we have a readme. Great. O(∩_∩)O

**Comment by whisperice** [comment]
Now we have a readme. Great. O(∩_∩)O

**Comment by liuxia0627** [comment]
Approve

**Review by liuxia0627 — APPROVED** [review]
Approved

**Review by whisperice — APPROVED** [review]

**Review by whisperice — APPROVED** [review]

**Pull request merged**
